IOC_TOP = /reg/g/pcds/epics/ioc/common/ads-ioc/R0.1.6
IOC_INSTANCE_PATH := $(shell pwd)

PROJECT_NAME = plc-kfe-vac
PROJECT_PATH := ../../plc-kfe-vac/plc-kfe-vac.tsproj
PLC = plc_kfe_vac

PYTMC_OPTS = 
PREFIX = PREFIX:

PRODUCTION_IOC := 1

include $(IOC_TOP)/iocBoot/templates/Makefile.base
