<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.0">
  <POU Name="FB_AD_TREATY_VGC" Id="{cc8265de-575f-4e4a-be6e-e4d049fa76c4}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_AD_TREATY_VGC
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_AD_TREATY_VGC">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>