<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.0">
  <POU Name="FB_ADTreatyGauge" Id="{14900fd8-a061-464a-85fc-d379f9247d46}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_ADTreatyGauge
VAR_INPUT
END_VAR
VAR_OUTPUT
	AD_Gauge : ST_VG;
END_VAR
VAR
	i_xAD_Press_OK AT %I* : BOOL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_ADTreatyGauge">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>