<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.12">
  <POU Name="PRG_VFS" Id="{cc87e4d4-e765-45d5-bfd0-460588216f75}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM PRG_VFS
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[fb_TV2K0_VFS_1(i_xOverrideMode := False, io_fbFFHWO =>);]]></ST>
    </Implementation>
    <LineIds Name="PRG_VFS">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>